name: app_turistica_front
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^0.13.5
  carousel_slider: ^5.0.0
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^10.1.0
  google_fonts: ^4.0.0
  animations: ^2.0.0
  cached_network_image: ^3.2.0
  avatar_glow: ^2.0.0
  image_picker: ^0.8.4+8
  shared_preferences: ^2.0.6
  flutter_rating_bar: ^4.0.0
  provider: ^6.1.2
  flutter_dotenv: ^5.0.2
  intl: ^0.17.0
  shimmer: ^2.0.0
  flutter_paypal: ^0.0.1
  paypal_sdk: ^1.0.9
  flutter_paypal_checkout: ^1.0.1
  flutter_braintree: ^4.0.0
  intl_phone_field: ^3.0.1
  geolocator: ^9.0.0
  flutter_map: ^4.0.0
  latlong2: ^0.8.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.10.0


flutter_icons:
  android: true
  image_path: "assets/Logopathi.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/Logopathi.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/1.jpg
    - assets/2.jpg
    - assets/3.jpg
    - assets/4.jpg
    - assets/5.jpg
    - assets/6.jpg
    - assets/7.jpg
    - assets/logoapp.png
    - assets/logo2.png
    - assets/Logopathi.png
    - assets/loginpathi.png
    - assets/logo.svg
    - assets/avatar.png
    - assets/icons/Cart Icon.svg
    - assets/icons/Bell.svg
    - assets/icons/Flash Icon.svg
    - assets/icons/Game Icon.svg
    - assets/icons/Gift Icon.svg
    - assets/icons/Discover.svg
    - assets/icons/Service.svg
    - assets/icons/Tag.svg
    - assets/icons/Plus Icon.svg
    - assets/images/Image Banner 3.png
    - assets/images/Image Banner 2.png
    - assets/icons/User Icon.svg
    - assets/images/
    - assets/icons/
    - assets/images/statue_of_liberty.png
    - assets/images/eiffel_tower.png
    - assets/images/great_wall_of_china.png
    - assets/images/sydney_opera_house.png